### ISSUE TITLE
關於Slide P.28問題

### ISSUE THREAD

**Issue by ysaaron** [simenkid/talks#1]
關於Slide P.28的內容介紹child_process的使用，但標題是否應修改為Run with Another Process更為恰當呢?

使用fork執行其他js在task tree裡面觀察到的是多了一個process，若是thread的話應該會是同一個process，但threadId不一樣

但這是我個人目前所知，或許有勘誤，還請多指正 : )

**Comment by simenkid** [comment]
Hi @ysaaron, 您說的是正確的。node 這支 fork() 的 API 名稱實在是取的很壞 XDD.... 
我這幾天人在國外，過兩天我回國後再修正投影片更新上來，感謝您的告知。

**Comment by simenkid** [comment]
Title fixed!
